const Chromy = require('../src')

let chromy = new Chromy({visible: true})
chromy.chain()
  .goto('http://example.com')
  .console(m => console.log(m))
  .setCookie({name: 'c1', value: 'v1'})
  .setCookie([{name: 'c2', value: 'v2'}, {name: 'c3', value: 'v3'}])
  .evaluate(_ => { console.log('AFTER SET:' + document.cookie) })
  .deleteCookie('c1')
  .deleteCookie(['c2', 'c3'])
  .evaluate(_ => { console.log('AFTER DELETED:' + document.cookie) })
  .end()
  .catch(e => console.log(e))
  .then(_ => chromy.close())

